"use client";

import { useRef } from "react";
import { Bold, BookOpen, Code2, FileText, Italic, Link2, List, Network, Type } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import type { StudyNote } from "@/types/note";

export type NoteLinkTarget = { kind: "nota" | "pdf" | "capitulo" | "conceito"; id: string; label: string };

export function NoteEditor({ note, onChange, linkTargets = [], onOpenLink }: { note: StudyNote; onChange: (note: StudyNote) => void; linkTargets?: readonly NoteLinkTarget[]; onOpenLink?: (target: NoteLinkTarget) => void }) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const insert = (before: string, after = "") => { const textarea = textareaRef.current; if (!textarea) return; const start = textarea.selectionStart; const end = textarea.selectionEnd; const selected = note.content.slice(start, end) || "texto"; const content = `${note.content.slice(0, start)}${before}${selected}${after}${note.content.slice(end)}`; onChange({ ...note, content }); requestAnimationFrame(() => { textarea.focus(); textarea.setSelectionRange(start + before.length, start + before.length + selected.length); }); };
  const insertLink = (target: NoteLinkTarget) => { const textarea = textareaRef.current; if (!textarea) return; const start = textarea.selectionStart; const token = `[[${target.kind}:${target.id}]]`; onChange({ ...note, content: `${note.content.slice(0, start)}${token}${note.content.slice(textarea.selectionEnd)}` }); requestAnimationFrame(() => { textarea.focus(); textarea.setSelectionRange(start + token.length, start + token.length); }); };
  const links = [...note.content.matchAll(/\[\[(nota|pdf|capitulo|conceito):([^\]]+)\]\]/g)].map((match) => ({ kind: match[1] as NoteLinkTarget["kind"], id: match[2], label: linkTargets.find((target) => target.kind === match[1] && target.id === match[2])?.label ?? match[2] }));
  const linkIcons = { nota: Link2, pdf: FileText, capitulo: BookOpen, conceito: Network };
  return <section aria-labelledby="note-editor-title" className="space-y-3 rounded-xl border bg-card p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="note-editor-title" className="text-lg font-semibold tracking-tight">Editor de nota</h2><span className="text-xs text-muted-foreground">Salvo automaticamente</span></div><Input aria-label="Título da nota" value={note.title} onChange={(event) => onChange({ ...note, title: event.target.value })} placeholder="Título da nota" /><div className="flex flex-wrap gap-1 rounded-lg border bg-muted/30 p-1"><Button type="button" variant="ghost" size="icon-sm" aria-label="Adicionar título" onClick={() => insert("## ")}><Type /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Adicionar negrito" onClick={() => insert("**", "**")}><Bold /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Adicionar itálico" onClick={() => insert("_", "_")}><Italic /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Adicionar lista" onClick={() => insert("- ")}><List /></Button><Button type="button" variant="ghost" size="icon-sm" aria-label="Adicionar código" onClick={() => insert("```\n", "\n```")}><Code2 /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="sm"><Link2 />Vincular</Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="max-h-72 overflow-y-auto">{linkTargets.map((target) => { const Icon = linkIcons[target.kind]; return <DropdownMenuItem key={`${target.kind}:${target.id}`} onSelect={() => insertLink(target)}><Icon />{target.label}</DropdownMenuItem>; })}{linkTargets.length === 0 && <DropdownMenuItem disabled>Nenhum destino disponível</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div><textarea ref={textareaRef} aria-label="Conteúdo da nota" value={note.content} onChange={(event) => onChange({ ...note, content: event.target.value })} placeholder="Escreva em Markdown e conecte notas, PDFs, capítulos e conceitos..." className="min-h-64 w-full resize-y rounded-lg border bg-background p-3 text-sm leading-6 outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" />{links.length > 0 && <div className="flex flex-wrap gap-2 border-t pt-3" aria-label="Links desta nota">{links.map((target, index) => { const Icon = linkIcons[target.kind]; return <Button key={`${target.kind}:${target.id}:${index}`} type="button" variant="outline" size="sm" onClick={() => onOpenLink?.(target)}><Icon />{target.label}</Button>; })}</div>}</section>;
}
