"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Cloud, Copy, Database, HardDrive, KeyRound, Laptop, LogOut, RefreshCw, ShieldCheck, UploadCloud, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { useAuth } from "./AuthProvider";
import { AuthClient } from "./AuthClient";
import { CloudSyncManager } from "@/features/sync/CloudSyncManager";
import type { ClientConflict, ClientSyncEntity } from "@/features/sync/types";
import type { CloudSyncState } from "./types";

type BackupItem = { id: string; sizeBytes: number; createdAt: string };
type ShareItem = { id: string; token: string; entity: string; recordId: string; createdAt: string };
type HistoryItem = { sequence:number; entity:string; recordId:string; operation:string; deviceId:string; createdAt:string };
const formatBytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`;

export function AccountPage() {
  const auth = useAuth();
  const [mode, setMode] = useState<"login" | "register" | "recover" | "reset">("login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const [sync, setSync] = useState<CloudSyncState>({ status: "idle", cursor: 0, pending: 0, uploadedBytes: 0 });
  const [conflicts, setConflicts] = useState<ClientConflict[]>([]); const [backups, setBackups] = useState<BackupItem[]>([]); const [shares, setShares] = useState<ShareItem[]>([]);
  const [history,setHistory]=useState<HistoryItem[]>([]);
  const [shareEntity, setShareEntity] = useState<ClientSyncEntity>("notes"); const [shareId, setShareId] = useState("");
  const [resetToken, setResetToken] = useState("");

  useEffect(() => { const parameters=new URLSearchParams(window.location.search);const verification=parameters.get("verify");const reset=parameters.get("reset");if(verification){setWorking(true);void AuthClient.verify(verification).then(()=>setMessage("Email verificado com sucesso.")).catch((cause)=>setError(cause instanceof Error?cause.message:"Verificação inválida.")).finally(()=>setWorking(false));window.history.replaceState({},"","/conta");}else if(reset){setResetToken(reset);setMode("reset");} }, []);

  const loadCloud = useCallback(async () => {
    if (!auth.session) return;
    const [state, conflictItems, backupData, shareData,historyData] = await Promise.all([CloudSyncManager.state(), CloudSyncManager.conflicts(), AuthClient.request<{backups:BackupItem[]}>("/backup"), AuthClient.request<{shares:ShareItem[]}>("/share"),AuthClient.request<{history:HistoryItem[]}>("/sync/history")]);
    setSync(state); setConflicts(conflictItems); setBackups(backupData.backups); setShares(shareData.shares);setHistory(historyData.history);
  }, [auth.session]);
  useEffect(() => { void loadCloud(); const listener=(event:Event)=>setSync((event as CustomEvent<CloudSyncState>).detail); window.addEventListener("studyai:cloud-sync",listener); return()=>window.removeEventListener("studyai:cloud-sync",listener); }, [loadCloud]);

  const submit = async () => { setWorking(true); setError(""); setMessage(""); try { if(mode==="login") await auth.login(email,password); else if(mode==="register"){const result=await auth.register(name,email,password);setMessage(result.verificationToken?`Conta criada. Token de verificação local: ${result.verificationToken}`:"Conta criada. Verifique seu email.");} else if(mode==="recover"){const result=await AuthClient.recover(email);setMessage(result.recoveryToken?`${result.message} Token local: ${result.recoveryToken}`:result.message);} else {await AuthClient.reset(resetToken,password);setMessage("Senha alterada. Entre com a nova senha.");setMode("login");window.history.replaceState({},"","/conta");} } catch(cause){setError(cause instanceof Error?cause.message:"Operação não concluída.");} finally{setWorking(false);} };

  if (auth.isLoading) return <p className="rounded-xl border p-8 text-center text-sm text-muted-foreground">Carregando sua conta…</p>;
  if (!auth.session) return <div className="mx-auto max-w-md space-y-5"><div><h1 className="text-2xl font-semibold tracking-tight">Conta StudyAI</h1><p className="mt-1 text-sm text-muted-foreground">Sincronize seu workspace entre seus dispositivos.</p></div><Card><CardHeader><CardTitle>{mode==="login"?"Entrar":mode==="register"?"Criar conta":mode==="reset"?"Definir nova senha":"Recuperar senha"}</CardTitle><CardDescription>Seus dados locais continuam disponíveis mesmo sem entrar.</CardDescription></CardHeader><CardContent className="space-y-3">{mode==="register"&&<Input aria-label="Nome" value={name} onChange={(event)=>setName(event.target.value)} placeholder="Seu nome"/>}{mode!=="reset"&&<Input aria-label="Email" type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="voce@email.com"/>}{mode!=="recover"&&<Input aria-label={mode==="reset"?"Nova senha":"Senha"} type="password" value={password} onChange={(event)=>setPassword(event.target.value)} placeholder="Ao menos 10 caracteres"/>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-600">{message}</p>}<Button className="w-full" onClick={()=>void submit()} disabled={working||(mode!=="reset"&&!email)||(mode!=="recover"&&!password)}>{working?"Aguarde…":mode==="login"?"Entrar":mode==="register"?"Cadastrar":mode==="reset"?"Alterar senha":"Enviar instruções"}</Button><div className="flex flex-wrap justify-center gap-2"><Button variant="link" size="sm" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Criar conta":"Já tenho conta"}</Button><Button variant="link" size="sm" onClick={()=>setMode("recover")}>Esqueci a senha</Button></div></CardContent></Card></div>;

  const profile=auth.session.user.profile;
  return <div className="space-y-6"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold tracking-tight">Conta e sincronização</h1><p className="mt-1 text-sm text-muted-foreground">Gerencie perfil, dispositivos, backups e conflitos.</p></div><Badge variant={sync.status==="error"?"destructive":"secondary"}><Cloud/>{sync.status==="syncing"?"Sincronizando":sync.status==="offline"?"Offline":sync.status==="error"?"Erro":"Sincronizado"}</Badge><Button variant="outline" onClick={()=>void auth.logout()}><LogOut/>Sair</Button></div>
    {auth.session.database==="memory"&&<p role="alert" className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-700 dark:text-amber-300"><AlertTriangle className="mr-2 inline size-4"/>Modo de desenvolvimento: configure `DATABASE_URL` para persistência cloud PostgreSQL.</p>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card className="gap-3 py-4"><CardContent className="px-4"><Cloud className="mb-2 size-5 text-primary"/><p className="text-xs text-muted-foreground">Último sync</p><p className="text-sm font-medium">{sync.lastSyncAt?new Date(sync.lastSyncAt).toLocaleString("pt-BR"):"Ainda não realizado"}</p></CardContent></Card><Card className="gap-3 py-4"><CardContent className="px-4"><UploadCloud className="mb-2 size-5 text-primary"/><p className="text-xs text-muted-foreground">Fila</p><p className="text-xl font-semibold">{sync.pending}</p></CardContent></Card><Card className="gap-3 py-4"><CardContent className="px-4"><HardDrive className="mb-2 size-5 text-primary"/><p className="text-xs text-muted-foreground">Enviado</p><p className="text-xl font-semibold">{formatBytes(sync.uploadedBytes)}</p></CardContent></Card><Card className="gap-3 py-4"><CardContent className="px-4"><Laptop className="mb-2 size-5 text-primary"/><p className="text-xs text-muted-foreground">Dispositivos</p><p className="text-xl font-semibold">{auth.session.devices.length}</p></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="size-5"/>Perfil</CardTitle><CardDescription>Preferências sincronizadas da sua conta.</CardDescription></CardHeader><CardContent className="space-y-3"><Input aria-label="Nome do perfil" defaultValue={profile?.name}/><Input aria-label="Foto do perfil" defaultValue={profile?.photoUrl} placeholder="URL da foto"/><div className="grid grid-cols-2 gap-2"><select aria-label="Idioma" defaultValue={profile?.language??"pt-BR"} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="pt-BR">Português</option><option value="en">English</option></select><select aria-label="Tema da conta" defaultValue={profile?.theme??"system"} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></div><Button onClick={async()=>{const container=document.querySelector('[aria-label="Nome do perfil"]') as HTMLInputElement;const photo=document.querySelector('[aria-label="Foto do perfil"]') as HTMLInputElement;const language=document.querySelector('[aria-label="Idioma"]') as HTMLSelectElement;const theme=document.querySelector('[aria-label="Tema da conta"]') as HTMLSelectElement;await AuthClient.updateProfile({name:container.value,photoUrl:photo.value,language:language.value,theme:theme.value});await auth.refresh();setMessage("Perfil atualizado.");}}>Atualizar perfil</Button>{!auth.session.user.emailVerified&&<Badge variant="outline">Email pendente de verificação</Badge>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><RefreshCw className="size-5"/>Cloud Sync</CardTitle><CardDescription>Incremental, versionado e offline-first.</CardDescription></CardHeader><CardContent className="space-y-3"><Progress value={sync.status==="syncing"?55:sync.status==="idle"?100:0}/>{sync.lastError&&<p role="alert" className="text-sm text-destructive">{sync.lastError}</p>}<Button onClick={async()=>{setSync((await CloudSyncManager.syncNow({ handshake: true })).state);await loadCloud();}} disabled={sync.status==="syncing"}><RefreshCw/>Sincronizar agora</Button><div className="space-y-2">{auth.session.devices.map((device)=><div key={device.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{device.deviceName}</p><p className="text-xs text-muted-foreground">Último acesso: {new Date(device.lastUsedAt).toLocaleString("pt-BR")}</p></div>)}</div></CardContent></Card></div>
    {conflicts.length>0&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-5 text-amber-500"/>Conflitos</CardTitle><CardDescription>Escolha uma versão ou mescle campos compatíveis.</CardDescription></CardHeader><CardContent className="space-y-3">{conflicts.map((conflict)=><div key={conflict.id} className="grid gap-3 rounded-lg border p-4 md:grid-cols-2"><div><p className="text-xs text-muted-foreground">Versão deste dispositivo</p><pre className="mt-2 max-h-32 overflow-auto rounded bg-muted p-2 text-xs">{JSON.stringify(conflict.local.data,null,2)}</pre><Button className="mt-2" size="sm" onClick={()=>void CloudSyncManager.resolve(conflict,"local").then(loadCloud)}>Usar esta versão</Button></div><div><p className="text-xs text-muted-foreground">Versão do outro dispositivo</p><pre className="mt-2 max-h-32 overflow-auto rounded bg-muted p-2 text-xs">{JSON.stringify(conflict.remote.data,null,2)}</pre><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={()=>void CloudSyncManager.resolve(conflict,"remote").then(loadCloud)}>Usar versão remota</Button><Button size="sm" variant="outline" onClick={()=>void CloudSyncManager.resolve(conflict,"merge").then(loadCloud)}>Mesclar</Button></div></div></div>)}</CardContent></Card>}
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-5"/>Backups</CardTitle><CardDescription>Criados automaticamente uma vez por dia.</CardDescription></CardHeader><CardContent className="space-y-3"><Button variant="outline" onClick={async()=>{await AuthClient.request("/backup",{method:"POST",body:JSON.stringify({action:"create"})});await loadCloud();}}>Criar backup agora</Button>{backups.length===0?<p className="text-sm text-muted-foreground">Nenhum backup.</p>:backups.map((backup)=><div key={backup.id} className="flex items-center gap-3 rounded-lg border p-3"><span className="flex-1 text-sm">{new Date(backup.createdAt).toLocaleString("pt-BR")} · {formatBytes(backup.sizeBytes)}</span><Button size="sm" variant="outline" onClick={async()=>{await AuthClient.request("/backup",{method:"POST",body:JSON.stringify({action:"restore",backupId:backup.id,deviceId:AuthClient.deviceId()})});await CloudSyncManager.syncNow();}}>Restaurar</Button></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Copy className="size-5"/>Compartilhamentos</CardTitle><CardDescription>Gere links revogáveis para registros já sincronizados.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 sm:grid-cols-[9rem_1fr_auto]"><select aria-label="Tipo para compartilhar" value={shareEntity} onChange={(event)=>setShareEntity(event.target.value as ClientSyncEntity)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="documents">PDF/material</option><option value="summaries">Resumo</option><option value="flashcards">Flashcards</option><option value="quizzes">Quiz</option><option value="notes">Nota</option><option value="mentor">Plano</option><option value="workspace">Workspace</option></select><Input aria-label="ID para compartilhar" value={shareId} onChange={(event)=>setShareId(event.target.value)} placeholder="ID do registro"/><Button disabled={!shareId} onClick={async()=>{await AuthClient.request("/share",{method:"POST",body:JSON.stringify({entity:shareEntity,recordId:shareId})});setShareId("");await loadCloud();}}>Compartilhar</Button></div>{shares.map((share)=><div key={share.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><span className="min-w-0 flex-1"><span className="block truncate font-medium">{share.entity} · {share.recordId}</span><button className="mt-1 text-xs text-primary underline" onClick={()=>void navigator.clipboard.writeText(`${location.origin}/compartilhar/${share.token}`)}>Copiar link</button></span><Button size="sm" variant="ghost" onClick={async()=>{await AuthClient.request("/share",{method:"DELETE",body:JSON.stringify({id:share.id})});await loadCloud();}}>Revogar</Button></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-5"/>Segurança</CardTitle><CardDescription>Altere email ou senha confirmando sua senha atual.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><SecurityForm kind="password"/><SecurityForm kind="email"/></CardContent></Card>
    <Card><CardHeader><CardTitle>Histórico de sincronização</CardTitle><CardDescription>Dispositivo, horário e alteração registrada na nuvem.</CardDescription></CardHeader><CardContent>{history.length===0?<p className="text-sm text-muted-foreground">Nenhuma alteração sincronizada.</p>:<div className="max-h-80 space-y-2 overflow-auto">{history.map((item)=><div key={item.sequence} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><Badge variant="outline">{item.operation==="delete"?"Exclusão":"Alteração"}</Badge><span className="min-w-0 flex-1 truncate">{item.entity} · {item.recordId}</span><span className="text-xs text-muted-foreground">{item.deviceId.slice(0,8)} · {new Date(item.createdAt).toLocaleString("pt-BR")}</span></div>)}</div>}</CardContent></Card>
    {message&&<p role="status" className="flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 className="size-4"/>{message}</p>}
  </div>;
}

function SecurityForm({kind}:{kind:"password"|"email"}){const[current,setCurrent]=useState("");const[value,setValue]=useState("");const[status,setStatus]=useState("");return <div className="space-y-2 rounded-lg border p-4"><p className="flex items-center gap-2 text-sm font-medium"><ShieldCheck className="size-4"/>{kind==="password"?"Alterar senha":"Alterar email"}</p><Input aria-label={kind==="password"?"Senha atual":"Senha para alterar email"} type="password" value={current} onChange={(event)=>setCurrent(event.target.value)} placeholder="Senha atual"/><Input aria-label={kind==="password"?"Nova senha":"Novo email"} type={kind==="password"?"password":"email"} value={value} onChange={(event)=>setValue(event.target.value)} placeholder={kind==="password"?"Nova senha":"novo@email.com"}/><Button size="sm" variant="outline" disabled={!current||!value} onClick={async()=>{try{if(kind==="password")await AuthClient.changePassword(current,value);else await AuthClient.changeEmail(current,value);setStatus("Alteração concluída.");}catch(error){setStatus(error instanceof Error?error.message:"Erro.");}}}>Atualizar</Button>{status&&<p className="text-xs text-muted-foreground">{status}</p>}</div>}
