"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BookOpenCheck, Check, Clock3, DoorOpen, GraduationCap, MessageSquare, Share2, Trash2, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/features/account/AuthProvider";
import { CollaborationClient } from "./CollaborationClient";
import { RoomDiscussion } from "./RoomDiscussion";
import { RoomMembers } from "./RoomMembers";
import { RoomResources } from "./RoomResources";
import { RoomSidebar } from "./RoomSidebar";
import type { CollaborativeResource, StudyRoom, StudyRoomSnapshot } from "./types";
import { TeacherAnalytics } from "@/features/analytics/components/TeacherAnalytics";

function inviteToken(value:string){try{const url=new URL(value);return url.searchParams.get("convite")??value;}catch{return value.trim();}}

export function CollaborationPage(){
  const auth=useAuth();const[rooms,setRooms]=useState<StudyRoom[]>([]);const[selectedId,setSelectedId]=useState<string>();const[snapshot,setSnapshot]=useState<StudyRoomSnapshot>();const[target,setTarget]=useState<CollaborativeResource>();const[tab,setTab]=useState("resources");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
  const loadRooms=useCallback(async(preferred?:string)=>{if(!auth.session)return;const data=await CollaborationClient.list();setRooms(data.rooms);setSelectedId((current)=>preferred??current??data.rooms[0]?.id);},[auth.session]);
  const loadRoom=useCallback(async()=>{if(!selectedId)return;try{setSnapshot(await CollaborationClient.room(selectedId));}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível abrir a sala.");}},[selectedId]);
  useEffect(()=>{void loadRooms();},[loadRooms]);
  useEffect(()=>{setTarget(undefined);if(!selectedId){setSnapshot(undefined);return;}void loadRoom();void CollaborationClient.heartbeat(selectedId,"studying");const timer=window.setInterval(()=>{if(document.visibilityState==="visible"){void CollaborationClient.heartbeat(selectedId,"studying").catch(()=>undefined);void loadRoom();}},8_000);return()=>window.clearInterval(timer);},[loadRoom,selectedId]);
  useEffect(()=>{if(!auth.session)return;const token=new URLSearchParams(window.location.search).get("convite");if(!token)return;window.history.replaceState({},"","/salas");setBusy(true);void CollaborationClient.join(token).then(({room})=>loadRooms(room.id)).catch((cause)=>setError(cause instanceof Error?cause.message:"Convite inválido.")).finally(()=>setBusy(false));},[auth.session,loadRooms]);
  const run=useCallback(async(operation:()=>Promise<void>,success:string)=>{setBusy(true);setError("");try{await operation();setMessage(success);await loadRooms();await loadRoom();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível concluir.");}finally{setBusy(false);}},[loadRoom,loadRooms]);
  const stats=useMemo(()=>snapshot?[{label:"Participantes",value:snapshot.members.length,icon:UsersRound},{label:"Conteúdos",value:snapshot.resources.length,icon:BookOpenCheck},{label:"Comentários",value:snapshot.comments.length,icon:MessageSquare},{label:"Online agora",value:snapshot.presence.length,icon:Activity}]:[],[snapshot]);
  if(auth.isLoading)return <p className="rounded-xl border p-10 text-center text-sm text-muted-foreground">Carregando colaboração…</p>;
  if(!auth.session)return <Card className="mx-auto max-w-lg"><CardHeader><CardTitle>Entre para colaborar</CardTitle><CardDescription>Salas, permissões e histórico precisam de uma identidade para manter cada alteração atribuída à pessoa certa.</CardDescription></CardHeader><CardContent><Button asChild><Link href="/conta">Entrar ou criar conta</Link></Button></CardContent></Card>;
  return <div className="space-y-5"><header className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Salas de estudo</h1><Badge variant="secondary">Colaboração</Badge></div><p className="mt-1 text-sm text-muted-foreground">Materiais, notas, decks, quizzes e Workspace em um espaço compartilhado.</p></div>{snapshot?.room.kind==="classroom"&&<Badge variant="outline"><GraduationCap/>Modo Professor</Badge>}</header>
    {(message||error)&&<div role={error?"alert":"status"} className={`flex items-center gap-2 rounded-lg border p-3 text-sm ${error?"border-destructive/30 text-destructive":"border-emerald-500/30 text-emerald-700 dark:text-emerald-300"}`}><Check className="size-4"/>{error||message}<button className="ml-auto text-xs underline" onClick={()=>{setMessage("");setError("");}}>Fechar</button></div>}
    <div className="grid items-start gap-5 lg:grid-cols-[17rem_minmax(0,1fr)]"><RoomSidebar rooms={rooms} selectedId={selectedId} busy={busy} onSelect={setSelectedId} onCreate={(name,kind)=>void run(async()=>{const{room}=await CollaborationClient.create({name,description:"",kind});setSelectedId(room.id);setSnapshot(await CollaborationClient.room(room.id));},"Sala criada.")} onJoin={(value)=>void run(async()=>{const{room}=await CollaborationClient.join(inviteToken(value));setSelectedId(room.id);setSnapshot(await CollaborationClient.room(room.id));},"Você entrou na sala.")}/>
      {!snapshot?<div className="rounded-xl border border-dashed p-12 text-center"><UsersRound className="mx-auto mb-4 size-9 text-muted-foreground"/><h2 className="font-semibold">Escolha ou crie uma sala</h2><p className="mt-1 text-sm text-muted-foreground">A colaboração aparece aqui sem alterar seu Workspace pessoal.</p></div>:<main className="min-w-0 space-y-5"><div className="flex flex-wrap items-start gap-3 rounded-xl border bg-card p-5"><div className="min-w-0 flex-1"><h2 className="truncate text-xl font-semibold">{snapshot.room.name}</h2><p className="mt-1 text-sm text-muted-foreground">{snapshot.room.description||`${snapshot.room.kind==="classroom"?"Turma":"Grupo de estudo"} · Você é ${snapshot.currentRole}`}</p></div><Badge variant="outline">{snapshot.currentRole}</Badge>{snapshot.currentRole==="admin"?<><Button variant="outline" size="sm" onClick={()=>void run(async()=>{const{url}=await CollaborationClient.invite(snapshot.room.id,"editor");await navigator.clipboard.writeText(url);},"Convite de editor copiado.")}><Share2/>Convidar</Button><Button variant="ghost" size="icon-sm" aria-label="Excluir sala" onClick={()=>{if(confirm("Excluir a sala e todo o histórico colaborativo?"))void(async()=>{setBusy(true);try{await CollaborationClient.deleteRoom(snapshot.room.id);setSnapshot(undefined);setSelectedId(undefined);setMessage("Sala excluída.");await loadRooms();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível excluir.");}finally{setBusy(false);}})();}}><Trash2/></Button></>:<Button variant="outline" size="sm" onClick={()=>{if(confirm("Sair desta sala?"))void(async()=>{setBusy(true);try{await CollaborationClient.leave(snapshot.room.id,auth.session!.user.id);setSnapshot(undefined);setSelectedId(undefined);setMessage("Você saiu da sala.");await loadRooms();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível sair.");}finally{setBusy(false);}})();}}><DoorOpen/>Sair</Button>}</div>
        <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map(({label,value,icon:Icon})=><Card key={label} className="gap-2 py-4"><CardContent className="flex items-center gap-3 px-4"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4"/></span><span><span className="block text-xl font-semibold">{value}</span><span className="text-xs text-muted-foreground">{label}</span></span></CardContent></Card>)}</div>
        <Tabs value={tab} onValueChange={setTab}><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="resources">Conteúdos</TabsTrigger><TabsTrigger value="discussion">Comentários</TabsTrigger><TabsTrigger value="people">Pessoas</TabsTrigger>{snapshot.room.kind==="classroom"&&snapshot.currentRole==="admin"&&<TabsTrigger value="analytics">Analytics</TabsTrigger>}<TabsTrigger value="activity">Histórico</TabsTrigger></TabsList>
          <TabsContent value="resources"><RoomResources snapshot={snapshot} onSelectComment={(resource)=>{setTarget(resource);setTab("discussion");}} onSave={async(value)=>{await run(()=>CollaborationClient.saveResource(snapshot.room.id,value).then(()=>undefined),value.id?"Conteúdo atualizado.":"Conteúdo compartilhado.");}} onRestore={async(resourceId,version)=>{await run(()=>CollaborationClient.restore(snapshot.room.id,resourceId,version).then(()=>undefined),"Versão restaurada.");}} onRemove={(id)=>{if(confirm("Remover este conteúdo da sala?"))void run(()=>CollaborationClient.removeResource(snapshot.room.id,id).then(()=>undefined),"Conteúdo removido.");}}/></TabsContent>
          <TabsContent value="discussion"><RoomDiscussion snapshot={snapshot} target={target} onComment={async(content,parentId)=>{await run(()=>CollaborationClient.comment(snapshot.room.id,{targetType:target?.type??"concept",targetId:target?.id??snapshot.room.id,parentId,content}).then(()=>undefined),"Comentário publicado.");}}/></TabsContent>
          <TabsContent value="people"><RoomMembers snapshot={snapshot} currentUserId={auth.session.user.id} onRole={(userId,role)=>void run(()=>CollaborationClient.setRole(snapshot.room.id,userId,role).then(()=>undefined),role==="admin"?"Administração transferida.":"Papel atualizado.")} onRemove={(userId)=>{if(confirm("Remover este participante da sala?"))void run(()=>CollaborationClient.removeMember(snapshot.room.id,userId).then(()=>undefined),"Participante removido.");}}/></TabsContent>
          <TabsContent value="analytics"><TeacherAnalytics snapshot={snapshot}/></TabsContent>
          <TabsContent value="activity"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Histórico auditável</h2><p className="mb-4 text-xs text-muted-foreground">Criações, edições, mudanças de papel e comentários.</p><div className="space-y-2">{snapshot.activity.map((item)=><div key={item.id} className="flex items-center gap-3 rounded-lg border p-3"><span className="flex size-8 items-center justify-center rounded-full bg-accent"><Clock3 className="size-4"/></span><span className="min-w-0 flex-1 text-sm"><span className="font-medium">{item.actorName}</span> · {item.action}</span><time className="text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString("pt-BR")}</time></div>)}</div></div></TabsContent>
        </Tabs></main>}</div>
  </div>;
}
