"use client";

import { useState } from "react";
import { MessageSquareReply, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CollaborationComment, CollaborativeResource, StudyRoomSnapshot } from "./types";

export function RoomDiscussion({snapshot,target,onComment}:{snapshot:StudyRoomSnapshot;target?:CollaborativeResource;onComment:(content:string,parentId?:string)=>Promise<void>}){const[content,setContent]=useState("");const[reply,setReply]=useState<CollaborationComment>();const canComment=snapshot.currentRole!=="reader";const targetId=target?.id??snapshot.room.id;const comments=snapshot.comments.filter((item)=>item.targetId===targetId);return <div className="mx-auto max-w-3xl space-y-4"><div><h2 className="font-semibold">Discussão · {target?.title??snapshot.room.name}</h2><p className="text-sm text-muted-foreground">Comentários ficam vinculados ao conteúdo e preservam as respostas.</p></div><div className="space-y-3">{comments.filter((item)=>!item.parentId).map((comment)=><CommentThread key={comment.id} comment={comment} replies={comments.filter((item)=>item.parentId===comment.id)} onReply={setReply}/>)}</div>{comments.length===0&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhum comentário neste item.</p>}{canComment?<form className="rounded-xl border bg-card p-3" onSubmit={(event)=>{event.preventDefault();void onComment(content,reply?.id).then(()=>{setContent("");setReply(undefined);});}}>{reply&&<div className="mb-2 flex items-center justify-between rounded-md bg-muted px-3 py-2 text-xs"><span>Respondendo a {reply.authorName}</span><button type="button" className="underline" onClick={()=>setReply(undefined)}>Cancelar</button></div>}<textarea aria-label="Novo comentário" value={content} onChange={(event)=>setContent(event.target.value)} className="min-h-24 w-full resize-y bg-transparent p-2 text-sm outline-none" placeholder="Escreva um comentário…"/><div className="flex justify-end"><Button size="sm" disabled={!content.trim()}><Send/>Enviar</Button></div></form>:<p className="rounded-lg bg-muted p-3 text-sm text-muted-foreground">Seu papel permite somente leitura.</p>}</div>}
function CommentThread({comment,replies,onReply}:{comment:CollaborationComment;replies:CollaborationComment[];onReply:(item:CollaborationComment)=>void}){return <article className="rounded-xl border bg-card p-4"><div className="flex items-start gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-accent text-[10px] font-semibold">{comment.authorName.slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{comment.authorName}</span><time className="text-xs text-muted-foreground">{new Date(comment.createdAt).toLocaleString("pt-BR")}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{comment.content}</p><Button size="xs" variant="ghost" className="mt-2" onClick={()=>onReply(comment)}><MessageSquareReply/>Responder</Button></div></div>{replies.length>0&&<div className="ml-8 mt-3 space-y-2 border-l pl-3">{replies.map((item)=><div key={item.id} className="rounded-lg bg-muted/60 p-3"><p className="text-xs font-medium">{item.authorName} · <span className="font-normal text-muted-foreground">{new Date(item.createdAt).toLocaleString("pt-BR")}</span></p><p className="mt-1 whitespace-pre-wrap text-sm">{item.content}</p></div>)}</div>}</article>}
