"use client";

import { useEffect, useState } from "react";
import { FileText, History, Layers3, MessageSquare, Pencil, Plus, RotateCcw, Save, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { CollaborationResourceType, CollaborativeResource, StudyRoomSnapshot } from "./types";
import { CollaborationClient } from "./CollaborationClient";

const labels:Record<CollaborationResourceType,string>={material:"Material",note:"Nota",flashcards:"Flashcards",quiz:"Quiz",workspace:"Workspace","study-plan":"Plano de estudo"};
export function RoomResources({snapshot,onSave,onRemove,onSelectComment,onRestore}:{snapshot:StudyRoomSnapshot;onSave:(value:{id?:string;type:CollaborationResourceType;title:string;data:unknown;expectedVersion?:number})=>Promise<void>;onRemove:(id:string)=>void;onSelectComment:(resource:CollaborativeResource)=>void;onRestore:(resourceId:string,version:number)=>Promise<void>}) {
  const canEdit=snapshot.currentRole==="admin"||snapshot.currentRole==="editor";const[editing,setEditing]=useState<CollaborativeResource>();const[draft,setDraft]=useState("");const[historyFor,setHistoryFor]=useState<string>();const[revisions,setRevisions]=useState<CollaborativeResource[]>([]);
  useEffect(()=>{setEditing(undefined);setDraft("");setHistoryFor(undefined);setRevisions([]);},[snapshot.room.id]);
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_20rem]"><section className="space-y-3"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{snapshot.resources.map((resource)=><article key={resource.id} className="group rounded-xl border bg-card p-4 transition-shadow hover:shadow-sm"><div className="flex items-start gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">{resource.type==="flashcards"?<Layers3 className="size-4"/>:<FileText className="size-4"/>}</span><div className="min-w-0 flex-1"><Badge variant="outline">{labels[resource.type]}</Badge><h3 className="mt-2 truncate text-sm font-semibold">{resource.title}</h3><p className="mt-1 text-xs text-muted-foreground">Versão {resource.version} · {new Date(resource.updatedAt).toLocaleString("pt-BR")}</p></div></div><div className="mt-4 flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={()=>onSelectComment(resource)}><MessageSquare/>Comentar</Button>{canEdit&&<Button size="sm" variant="ghost" onClick={()=>{setEditing(resource);setDraft(typeof resource.data==="object"&&resource.data!==null&&"content" in resource.data?String((resource.data as {content:unknown}).content):JSON.stringify(resource.data,null,2));}}><Pencil/>Editar</Button>}{canEdit&&<Button size="icon-sm" variant="ghost" aria-label={`Histórico de ${resource.title}`} onClick={()=>void CollaborationClient.revisions(snapshot.room.id,resource.id).then(({revisions:items})=>{setRevisions(items);setHistoryFor(resource.id);})}><History/></Button>}{canEdit&&<Button size="icon-sm" variant="ghost" aria-label={`Remover ${resource.title}`} onClick={()=>onRemove(resource.id)}><Trash2/></Button>}</div></article>)}</div>{snapshot.resources.length===0&&<div className="rounded-xl border border-dashed p-10 text-center"><Layers3 className="mx-auto mb-3 size-7 text-muted-foreground"/><p className="font-medium">A sala ainda não possui conteúdo</p><p className="mt-1 text-sm text-muted-foreground">Compartilhe um material, nota, deck, quiz ou layout.</p></div>}</section>
    {canEdit&&<aside className="h-fit rounded-xl border bg-card p-4">{historyFor?<><h2 className="font-semibold">Histórico de versões</h2><p className="mb-4 text-xs text-muted-foreground">Restaure uma edição anterior sem apagar a atual.</p>{revisions.length===0?<p className="text-sm text-muted-foreground">Nenhuma versão anterior.</p>:<div className="space-y-2">{revisions.map((revision)=><div key={revision.version} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><span className="flex-1">Versão {revision.version}<span className="block text-xs text-muted-foreground">{new Date(revision.updatedAt).toLocaleString("pt-BR")}</span></span><Button size="xs" variant="outline" onClick={()=>void onRestore(historyFor,revision.version)}><RotateCcw/>Restaurar</Button></div>)}</div>}<Button className="mt-3" size="sm" variant="ghost" onClick={()=>setHistoryFor(undefined)}>Voltar</Button></>:<><h2 className="font-semibold">{editing?"Editar recurso":"Compartilhar recurso"}</h2><p className="mb-4 text-xs text-muted-foreground">Edições usam versão para evitar sobrescritas.</p><ResourceForm resource={editing} draft={draft} setDraft={setDraft} onCancel={()=>{setEditing(undefined);setDraft("");}} onSubmit={async(value)=>{await onSave(value);setEditing(undefined);setDraft("");}}/></>}</aside>}</div>;
}

function ResourceForm({resource,draft,setDraft,onSubmit,onCancel}:{resource?:CollaborativeResource;draft:string;setDraft:(value:string)=>void;onSubmit:(value:{id?:string;type:CollaborationResourceType;title:string;data:unknown;expectedVersion?:number})=>Promise<void>;onCancel:()=>void}){const[type,setType]=useState<CollaborationResourceType>(resource?.type??"note");const[title,setTitle]=useState(resource?.title??"");useEffect(()=>{setType(resource?.type??"note");setTitle(resource?.title??"");},[resource]);return <form className="space-y-3" onSubmit={(event)=>{event.preventDefault();void onSubmit({id:resource?.id,type,title,data:{content:draft},expectedVersion:resource?.version});}}><select aria-label="Tipo do recurso" value={type} disabled={Boolean(resource)} onChange={(event)=>setType(event.target.value as CollaborationResourceType)} className="h-10 w-full rounded-lg border bg-background px-3 text-sm">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Input aria-label="Título do recurso" value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="Título" required/><textarea aria-label="Conteúdo compartilhado" value={draft} onChange={(event)=>setDraft(event.target.value)} className="min-h-40 w-full resize-y rounded-lg border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring/40" placeholder="Conteúdo, instruções ou referência…"/><div className="flex gap-2"><Button type="submit" size="sm" disabled={!title.trim()}>{resource?<Save/>:<Plus/>}{resource?"Salvar":"Adicionar"}</Button>{resource&&<Button type="button" size="sm" variant="ghost" onClick={onCancel}>Cancelar</Button>}</div></form>}
