"use client";

import { Crown, Radio, UserMinus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { CollaborationRole, StudyRoomSnapshot } from "./types";

const labels:Record<CollaborationRole,string>={admin:"Administrador",editor:"Editor",commenter:"Comentador",reader:"Leitor"};
export function RoomMembers({snapshot,currentUserId,onRole,onRemove}:{snapshot:StudyRoomSnapshot;currentUserId:string;onRole:(userId:string,role:CollaborationRole)=>void;onRemove:(userId:string)=>void}) {
  const canManage=snapshot.currentRole==="admin";
  return <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Participantes</h2><p className="text-xs text-muted-foreground">Papéis controlam leitura, comentários e edição.</p></div><Badge variant="secondary">{snapshot.members.length}</Badge></div><div className="space-y-2">{snapshot.members.map((member)=>{const progress=snapshot.progress.filter((item)=>item.userId===member.userId);const completed=progress.reduce((sum,item)=>sum+item.completed,0);const total=progress.reduce((sum,item)=>sum+item.total,0);return <div key={member.userId} className="flex flex-wrap items-center gap-3 rounded-lg border p-3"><span className="flex size-9 items-center justify-center rounded-full bg-accent text-xs font-semibold">{member.name.slice(0,2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{member.name}{member.userId===currentUserId?" (você)":""}</span><span className="block truncate text-xs text-muted-foreground">{member.email}{total>0?` · ${completed}/${total} concluídos`:""}</span></span>{canManage&&member.userId!==currentUserId?<><select aria-label={`Papel de ${member.name}`} value={member.role} onChange={(event)=>onRole(member.userId,event.target.value as CollaborationRole)} className="h-8 rounded-md border bg-background px-2 text-xs"><option value="admin">Administrador</option><option value="editor">Editor</option><option value="commenter">Comentador</option><option value="reader">Leitor</option></select><Button size="icon-sm" variant="ghost" aria-label={`Remover ${member.name}`} onClick={()=>onRemove(member.userId)}><UserMinus/></Button></>:<Badge variant="outline">{member.role==="admin"&&<Crown/>}{labels[member.role]}</Badge>}</div>})}</div></section>
    <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Estudando agora</h2><p className="mb-4 text-xs text-muted-foreground">Presença expira automaticamente após 45 segundos.</p>{snapshot.presence.length===0?<p className="rounded-lg border border-dashed p-5 text-center text-sm text-muted-foreground">Ninguém online agora.</p>:<div className="space-y-2">{snapshot.presence.map((person)=><div key={person.userId} className="flex items-center gap-3 rounded-lg border p-3"><span className="relative flex size-9 items-center justify-center rounded-full bg-accent text-xs font-semibold">{person.name.slice(0,2).toUpperCase()}<span className="absolute -bottom-0.5 -right-0.5 size-3 rounded-full border-2 border-card bg-emerald-500"/></span><span className="flex-1 text-sm"><span className="block font-medium">{person.name}</span><span className="text-xs text-muted-foreground">{person.status==="typing"?"Digitando":person.status==="away"?"Ausente":"Estudando"}</span></span><Radio className="size-4 text-emerald-500"/></div>)}</div>}</section></div>;
}
