import { BookOpen, Bot, Brain, Cloud, Cpu, FileQuestion, FolderOpen, Library, MessageCircleQuestion, Search, Sparkles } from "lucide-react";

export const helpTopics = [
  {
    id: "importar",
    title: "Como importar materiais",
    description: "Adicione um arquivo ou uma pasta e acompanhe o processamento.",
    keywords: ["pdf", "docx", "pptx", "arquivo", "pasta"],
    icon: FolderOpen,
    href: "/importar",
    steps: ["Abra Importar.", "Arraste arquivos ou escolha uma pasta.", "Revise a lista e selecione Importar.", "Abra o material na Biblioteca quando o processamento terminar."],
  },
  {
    id: "biblioteca",
    title: "Organizar e encontrar materiais",
    description: "Use filtros, pesquisa, tags e ações em lote na Biblioteca.",
    keywords: ["biblioteca", "organizar", "tags", "mover"],
    icon: Library,
    href: "/biblioteca",
    steps: ["Pesquise pelo nome, matéria ou tema.", "Use os filtros para reduzir a lista.", "Selecione vários itens para mover, favoritar ou excluir.", "Escolha Estudar para abrir o Workspace."],
  },
  {
    id: "workspace",
    title: "Estudar no Workspace",
    description: "Combine material, Tutor, notas, revisão e mapa em painéis.",
    keywords: ["workspace", "painel", "layout", "estudo"],
    icon: BookOpen,
    href: "/estudo",
    steps: ["Escolha um tema na navegação lateral.", "Selecione um layout para leitura, revisão ou exercícios.", "Redimensione ou minimize painéis conforme necessário.", "Seu layout e posição de leitura são salvos automaticamente."],
  },
  {
    id: "tutor",
    title: "Conversar com o Tutor",
    description: "Faça perguntas usando somente o contexto dos seus materiais.",
    keywords: ["tutor", "ia", "pergunta", "contexto"],
    icon: Bot,
    href: "/tutor",
    steps: ["Abra um tema para definir o contexto.", "Digite uma pergunta ou use uma ação rápida.", "Confira os materiais usados na resposta.", "Continue na mesma conversa para preservar o histórico."],
  },
  {
    id: "mentor",
    title: "Usar o Mentor",
    description: "Inicie uma sessão guiada com perguntas e recomendações adaptativas.",
    keywords: ["mentor", "sessão", "socrático", "objetivo"],
    icon: Sparkles,
    href: "/estudo",
    steps: ["Abra o painel Mentor no Workspace.", "Escolha matéria e tema.", "Responda às perguntas com suas palavras.", "Use a correção e o plano sugerido para continuar."],
  },
  {
    id: "flashcards",
    title: "Criar e revisar Flashcards",
    description: "Gere cartões do conteúdo extraído e registre acertos e erros.",
    keywords: ["flashcards", "cartões", "revisão"],
    icon: Brain,
    href: "/estudo",
    steps: ["Abra um tema com conteúdo extraído.", "Abra Flashcards e selecione Gerar.", "Mostre a resposta somente depois de tentar.", "Marque Acertei ou Errei para agendar a próxima revisão."],
  },
  {
    id: "quiz",
    title: "Fazer um Quiz",
    description: "Gere questões do tema e acompanhe o resultado real.",
    keywords: ["quiz", "questões", "exercícios", "prova"],
    icon: FileQuestion,
    href: "/estudo",
    steps: ["Abra o painel Quiz em um tema processado.", "Gere as questões.", "Responda uma alternativa por vez.", "Revise a explicação e o relatório final."],
  },
  {
    id: "pesquisa",
    title: "Pesquisa e comandos rápidos",
    description: "Use Ctrl + K para encontrar conteúdo ou executar ações.",
    keywords: ["pesquisa", "buscar", "atalho", "comando"],
    icon: Search,
    href: "/",
    steps: ["Pressione Ctrl + K em qualquer tela.", "Digite um material, conceito, página ou ação.", "Use as setas para navegar e Enter para abrir."],
  },
  {
    id: "sincronizacao",
    title: "Sincronização entre dispositivos",
    description: "Entenda o modo offline, a fila e a retomada automática.",
    keywords: ["cloud", "sincronização", "offline", "dispositivo"],
    icon: Cloud,
    href: "/conta",
    steps: ["Entre na mesma conta em cada dispositivo.", "Continue estudando mesmo sem conexão.", "Ao voltar à internet, aguarde o status Sincronizado.", "Resolva conflitos na página Conta quando solicitado."],
  },
  {
    id: "ia-local",
    title: "Configurar IA local",
    description: "Use Ollama no seu computador sem enviar o contexto a um provider cloud.",
    keywords: ["ollama", "ia local", "modelo", "provider", "offline"],
    icon: Cpu,
    href: "/configuracoes",
    steps: ["Instale e inicie o Ollama no computador.", "Baixe ao menos um modelo compatível.", "Abra Configurações, IA e selecione Ollama.", "Teste a conexão e escolha um dos modelos encontrados automaticamente."],
  },
  {
    id: "faq",
    title: "Perguntas frequentes",
    description: "Respostas rápidas sobre dados, autosave, offline e privacidade.",
    keywords: ["faq", "dúvidas", "salvar", "offline", "privacidade", "dados"],
    icon: MessageCircleQuestion,
    href: "/configuracoes",
    steps: ["O StudyAI salva alterações automaticamente.", "O modo offline usa o banco local isolado da conta atual.", "Arquivos físicos não são enviados diretamente à IA.", "Telemetria é opcional e nunca inclui materiais, notas ou conversas."],
  },
] as const;
